site_name: CompTIA A+ Study Guide
theme:
  name: material
  palette:
    - scheme: default
      primary: teal
      accent: deep orange
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: teal
      accent: deep orange
      toggle:
        icon: material/white-balance-sunny
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.sections
    - navigation.tabs
    - toc.integrate
    - content.code.copy
    - navigation.footer  

nav:
  - Home: index.md
  - Exam Objectives: exam-objectives.md
  - Core 1:
      - 1.0 Mobile Devices:
          - Overview: core1/1.0-mobile-devices/index.md
          - Laptop Hardware: core1/1.0-mobile-devices/1.1-laptop-hardware.md
          - Connecting Devices: core1/1.0-mobile-devices/1.2-connecting-mobile-devices.md
          - Accessories: core1/1.0-mobile-devices/1.2-mobile-device-accessories.md
          - Mobile Device Management: core1/1.0-mobile-devices/1.3-mobile-device-management.md
          - Mobile Networks: core1/1.0-mobile-devices/1.3-mobile-device-networks.md
      - 2.0 Networking: core1/networking.md
      - 3.0 Hardware: core1/hardware.md
      - 4.0 Virtualization: core1/virtualization.md
      - 5.0 Troubleshooting: core1/troubleshooting.md
  - Core 2:
      - 1.0 Operating Systems: core2/1.0-operating-systems-overview.md
      - 2.0 Security: core2/2.0-security-overview.md
      - 3.0 Software Troubleshooting: core2/3.0-software-troubleshooting-overview.md

markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - pymdownx.superfences
  - pymdownx.details
  - codehilite

extra_javascript:
  - js/print-button.js
extra_css:
  - css/print-button.css